# Generated by Django 4.0.5 on 2022-07-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='programming_language',
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.language', verbose_name='Язык'),
        ),
    ]
